language: java
jdk:
  - openjdk11

services:
  - docker

sudo: required
git:
  depth: 3

env:
  global:
    - GRADLE_CLI_OPTS="--console=plain --stacktrace --quiet"

before_install:
  - sudo /etc/init.d/mysql stop
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` > /tmp/docker-compose
  - chmod +x /tmp/docker-compose
  - sudo mv /tmp/docker-compose /usr/local/bin
  - APP_VERSION=$([ -n "${TRAVIS_TAG}" ] && echo "${TRAVIS_TAG#*v}" || echo "${TRAVIS_BRANCH##*/}")
  - DOCKER_IMAGE_VERSION=$([ -n "${TRAVIS_TAG}" ] && echo "${TRAVIS_TAG}" || echo "${TRAVIS_BRANCH##*/}")

install:
  - git clone https://github.com/FAForever/faf-stack.git faf-stack
    && pushd faf-stack
    && git checkout 8686b24
    && cp -r config.template config
    && cp .env.template .env
    && ./scripts/init-db.sh
    && popd

script:
  - chmod +x gradlew && ./gradlew ${GRADLE_CLI_OPTS} build -Pversion=${APP_VERSION}

after_success:
  - ./gradlew ${GRADLE_CLI_OPTS} jacocoTestReport coveralls
  - export IMAGE_TAG=faf-java-api;
  - export REPO=faforever/faf-java-api;
  - if [ -n "${TRAVIS_TAG}" -o "${TRAVIS_BRANCH}" == "develop" ]; then
    docker build -t ${IMAGE_TAG} . &&
    echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin &&
    docker tag ${IMAGE_TAG} ${REPO}:${DOCKER_IMAGE_VERSION} &&
    docker push ${REPO};
    fi
# TODO Codacy coverage reporter does not yet support Java 9. See https://github.com/codacy/codacy-coverage-reporter/issues/76
#      ./gradlew sendCoverageToCodacy;

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - /home/travis/build/FAForever/faf-java-api/build/cache/
