language: java

services:
  - docker

sudo: required
git:
  depth: 3

before_install:
  - sudo /etc/init.d/mysql stop
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.10.0/docker-compose-`uname -s`-`uname -m` > /tmp/docker-compose
  - chmod +x /tmp/docker-compose
  - sudo mv /tmp/docker-compose /usr/local/bin

install:
  - git clone https://github.com/FAForever/faf-stack.git faf-stack
      && pushd faf-stack
      && git checkout 024322dfef9c600f458b91baeb1b4a7326b31580
      && cp -r config.template config
      && popd
  - docker-compose -f faf-stack/docker-compose.yml up -d faf-db

script:
  - chmod +x gradlew && ./gradlew build --info

after_success:
  - ./gradlew jacocoTestReport coveralls
  - if [ -n "${TRAVIS_TAG}" ]; then
      ./gradlew pushDockerImage;
    fi
  - if [ "${TRAVIS_BRANCH}" == "develop" ]; then
      ./gradlew jacocoTestReport sendCoverageToCodacy;
    fi

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
