faf-api:
  version: dev
  jwt:
    secret: ${JWT_SECRET:banana}
  map:
    target-directory: ${MAP_UPLOAD_PATH:build/cache/map/maps}
    directory-preview-path-small: ${MAP_PREVIEW_PATH_SMALL:build/cache/map_previews/small}
    directory-preview-path-large: ${MAP_PREVIEW_PATH_LARGE:build/cache/map_previews/large}
    small-previews-url-format: ${MAP_SMALL_PREVIEWS_URL_FORMAT:http://test.content.faforever.com/faf/vault/map_previews/small/%s}
    large-previews-url-format: ${MAP_LARGE_PREVIEWS_URL_FORMAT:http://test.content.faforever.com/faf/vault/map_previews/large/%s}
    download-url-format: ${MAP_DOWNLOAD_URL_FORMAT:http://test.content.faforever.com/faf/vault/maps/%s}
  mod:
    download-url-format: ${MOD_DOWNLOAD_URL_FORMAT:http://test.content.faforever.com/faf/vault/mods/%s}
    preview-url-format: ${MOD_PREVIEW_URL_FORMAT:http://test.content.faforever.com/faf/vault/mods/%s}
  replay:
    download-url-format: ${REPLAY_DOWNLOAD_URL_FORMAT:http://content.test.faforever.com/faf/vault/replay_vault/replay.php?id=%s}
  featured-mods:
    file-url-format: ${FEATURED_MOD_URL_FORMAT:http://content.test.faforever.com/faf/updaterNew/%s/%s}
  git-hub:
    access-token: ${GITHUB_ACCESS_TOKEN:none}
    deployment-environment: ${GITHUB_DEPLOYMENT_ENVIRONMENT:development}
    webhook-secret: ${GITHUB_WEBHOOK_SECRET:none}
  deployment:
    forged-alliance-exe-path: ${FORGED_ALLIANCE_EXE_PATH}
    repositories-directory: ${REPOSITORIES_DIRECTORY:build/cache/repos}
    featured-mods-target-directory: ${FEATURED_MODS_TARGET_DIRECTORY:build/cache/deployment}
    # TODO make this runtime configuration
    configurations:
      - repositoryUrl: https://github.com/FAForever/fa.git
        branch: deploy/faf
        modName: faf
        modFilesExtension: nx2
        replaceExisting: false
      - repositoryUrl: https://github.com/FAForever/fa.git
        branch: deploy/fafbeta
        modName: fafbeta
        modFilesExtension: nx4
        replaceExisting: true
      - repositoryUrl: https://github.com/FAForever/fa.git
        branch: deploy/fafdevelop
        modName: fafdevelop
        modFilesExtension: nx5
        replaceExisting: true
  clan:
    website-url-format: ${CLAN_WEBSITE_URL_FORMAT:http://clans.test.faforever.com/clan/%s}

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS:localhost}/${DATABASE_NAME:faf}?useSSL=false
    name: faf
    username: ${DATABASE_USERNAME:faf-api}
    password: ${DATABASE_PASSWORD:banana}
  jpa:
    show-sql: true

logging:
  level:
    com.faforever.api: trace
