faf-api:
  jwt:
    secretKeyPath: ${JWT_PRIVATE_KEY_PATH}
    publicKeyPath: ${JWT_PUBLIC_KEY_PATH}
  map:
    target-directory: ${MAP_UPLOAD_PATH}
    directory-preview-path-small: ${MAP_PREVIEW_PATH_SMALL}
    directory-preview-path-large: ${MAP_PREVIEW_PATH_LARGE}
    small-previews-url-format: ${MAP_SMALL_PREVIEWS_URL_FORMAT}
    large-previews-url-format: ${MAP_LARGE_PREVIEWS_URL_FORMAT}
    download-url-format: ${MAP_DOWNLOAD_URL_FORMAT}
  mod:
    download-url-format: ${MOD_DOWNLOAD_URL_FORMAT}
    preview-url-format: ${MOD_PREVIEW_URL_FORMAT}
    target-directory: ${MOD_TARGET_DIRECTORY}
    thumbnail-target-directory: ${MOD_THUMBNAIL_TARGET_DIRECTORY}
  replay:
    download-url-format: ${REPLAY_DOWNLOAD_URL_FORMAT}
  tutorial:
    thumbnail-url-format: ${TUTORIAL_THUMBNAIL_URL_FORMAT}
  avatar:
    download-url-format: ${AVATAR_DOWNLOAD_URL_FORMAT}
    target-directory: ${AVATAR_TARGET_DIRECTORY}
    allowed-extensions: ${AVATAR_ALLOWED_FILE_EXTENSIONS}
  featured-mod:
    file-url-format: ${FEATURED_MOD_URL_FORMAT}
    bireus-url-format: ${FEATURED_MOD_BIREUS_URL_FORMAT}
  git-hub:
    deployment-environment: ${GITHUB_DEPLOYMENT_ENVIRONMENT:production}
  deployment:
    forged-alliance-exe-path: ${FORGED_ALLIANCE_EXE_PATH}
    repositories-directory: ${REPOSITORIES_DIRECTORY}
    featured-mods-target-directory: ${FEATURED_MODS_TARGET_DIRECTORY}
    testing-exe-upload-key: ${TESTING_EXE_UPLOAD_KEY}
    forged-alliance-beta-exe-path: ${EXE_UPLOAD_BETA_PATH}
    forged-alliance-develop-exe-path: ${EXE_UPLOAD_DEVELOP_PATH}
  clan:
    website-url-format: ${CLAN_WEBSITE_URL_FORMAT}
  mail:
    from-email-name: ${EMAIL_FROM_NAME}
    from-email-address: ${EMAIL_FROM_ADDRESS}
  registration:
    activation-url-format: ${ACTIVATION_URL_FORMAT}
    subject: ${REGISTRATION_EMAIL_SUBJECT}
    html-format: ${REGISTRATION_EMAIL_BODY}
  password-reset:
    password-reset-url-format: ${PASSWORD_RESET_URL_FORMAT}
    subject: ${PASSWORD_RESET_EMAIL_SUBJECT}
    html-format: ${PASSWORD_RESET_EMAIL_BODY}
  steam:
    realm: ${STEAM_REALM}
    api-key: ${STEAM_API_KEY}
  link-to-steam:
    steam-redirect-url-format: ${STEAM_LINK_REDIRECT_URL}

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS}/${DATABASE_NAME}?useSSL=false
    name: faf
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL}
        username: ${ADMIN_SERVER_USERNAME}
        password: ${ADMIN_SERVER_PASSWORD}
        instance:
          metadata:
            user:
              name: ${ADMIN_CLIENT_USERNAME}
              password: ${ADMIN_CLIENT_PASSWORD}

logging:
  path: ${LOG_FILE_DIRECTORY:/tmp}
