faf-api:
  version: dev
  jwt:
    secretKeyPath: ${JWT_PRIVATE_KEY_PATH:test-pki-private.key}
    publicKeyPath: ${JWT_PUBLIC_KEY_PATH:test-pki-public.key}
  map:
    target-directory: ${MAP_UPLOAD_PATH:build/cache/map/maps}
    directory-preview-path-small: ${MAP_PREVIEW_PATH_SMALL:build/cache/map_previews/small}
    directory-preview-path-large: ${MAP_PREVIEW_PATH_LARGE:build/cache/map_previews/large}
    small-previews-url-format: ${MAP_SMALL_PREVIEWS_URL_FORMAT:http://test.content.faforever.com/faf/vault/map_previews/small/%s}
    large-previews-url-format: ${MAP_LARGE_PREVIEWS_URL_FORMAT:http://test.content.faforever.com/faf/vault/map_previews/large/%s}
    download-url-format: ${MAP_DOWNLOAD_URL_FORMAT:http://test.content.faforever.com/faf/vault/maps/%s}
  mod:
    download-url-format: ${MOD_DOWNLOAD_URL_FORMAT:http://test.content.faforever.com/faf/vault/mods/%s}
    preview-url-format: ${MOD_PREVIEW_URL_FORMAT:http://test.content.faforever.com/faf/vault/mods/%s}
  replay:
    download-url-format: ${REPLAY_DOWNLOAD_URL_FORMAT:http://content.test.faforever.com/replays/%s}
  tutorial:
    thumbnail-url-format: ${TUTORIAL_THUMBNAIL_URL_FORMAT:http://content.test.faforever.com/faf/tutorials/thumbs/%s}
  avatar:
    download-url-format: ${AVATAR_DOWNLOAD_URL_FORMAT:http://content.test.faforever.com/faf/avatars/%s}
    target-directory: ${AVATAR_TARGET_DIRECTORY:build/cache/avatars}
    allowed-extensions: ${AVATAR_ALLOWED_FILE_EXTENSIONS:png}
  featured-mod:
    file-url-format: ${FEATURED_MOD_URL_FORMAT:http://content.test.faforever.com/faf/updaterNew/%s/%s}
    bireus-url-format: ${FEATURED_MOD_BIREUS_URL_FORMAT:https://content.test.faforever.com/repositories/%s}
  git-hub:
    deployment-environment: ${GITHUB_DEPLOYMENT_ENVIRONMENT:development}
  deployment:
    forged-alliance-exe-path: ${FORGED_ALLIANCE_EXE_PATH}
    repositories-directory: ${REPOSITORIES_DIRECTORY:build/cache/repos}
    featured-mods-target-directory: ${FEATURED_MODS_TARGET_DIRECTORY:build/cache/deployment}
    testing-exe-upload-key: ${TESTING_EXE_UPLOAD_KEY:banana}
    forged-alliance-beta-exe-path: ${EXE_UPLOAD_BETA_PATH:build/exe/beta}
    forged-alliance-develop-exe-path: ${EXE_UPLOAD_DEVELOP_PATH:build/exe/develop}
  clan:
    website-url-format: ${CLAN_WEBSITE_URL_FORMAT:http://clans.test.faforever.com/clan/%s}
  mail:
    from-email-name: ${EMAIL_FROM_NAME:FAForever}
    from-email-address: ${EMAIL_FROM_ADDRESS:faf@example.com}
  registration:
    activation-url-format: ${ACTIVATION_URL_FORMAT:http://localhost:8020/account/activate?username=%s&token=%s}
    subject: ${REGISTRATION_EMAIL_SUBJECT:FAF user registration}
    html-format: ${REGISTRATION_EMAIL_BODY:Registration email body}
  password-reset:
    password-reset-url-format: ${PASSWORD_RESET_URL_FORMAT:http://localhost:8020/account/password/confirmReset?username=%s&token=%s}
    subject: ${PASSWORD_RESET_EMAIL_SUBJECT:FAF password reset}
    html-format: ${PASSWORD_RESET_EMAIL_BODY:Registration email body}
  steam:
    realm: ${STEAM_REALM:http://localhost}
    api-key: ${STEAM_API_KEY:banana}
    link-to-steam-redirect-url-format: ${STEAM_LINK_REDIRECT_URL_FORMAT:http://localhost:8010/users/linkToSteam?token=%s}
    steam-password-reset-redirect-url-format: ${STEAM_PASSWORD_RESET_REDIRECT_URL_FORMAT:http://localhost:8010/users/requestPasswordResetViaSteam}

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS:127.0.0.1}/${DATABASE_NAME:faf}?useSSL=false
    name: faf
    username: ${DATABASE_USERNAME:faf-java-api}
    password: ${DATABASE_PASSWORD:banana}
  jpa:
    show-sql: true
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:8030}
        username: ${ADMIN_SERVER_USERNAME:admin}
        password: ${ADMIN_SERVER_PASSWORD:banana}
        instance:
          metadata:
            user:
              name: ${ADMIN_CLIENT_USERNAME:faf-java-api}
              password: ${ADMIN_CLIENT_PASSWORD:banana}
logging:
  level:
    com.faforever.api: debug

