faf-api:
  jwt-secret: ${JWT_SECRET}

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS}/${DATABASE_NAME}?useSSL=false
    name: faf_lobby
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false
